image: golang:1.12

artifacts:
  paths:
    - bin/

stages:
  - test
  - build

before_script:
  - make dep

unit_tests:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make build
